site_name: Open Strategy Games Resources
site_url: https://openstrategygames.github.io/
site_description: A reference for faction-scale, argument-driven play
site_author: Roberto Bisceglie
repo_url: https://github.com/openstrategygames/osg_resources
repo_name: openstrategygames/osg_resources
edit_uri: ""

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/logo.svg
  palette:
    - scheme: default
      primary: white
      accent: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: grey
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.suggest
    - content.code.copy
    - toc.follow

extra_css:
  - assets/stylesheets/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/openstrategygames/osg_resources

copyright: >
  The Open Strategy Games Resources are licensed under
  <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a>.</br>
  Logo by Delapouite under
  <a href="https://creativecommons.org/licenses/by/3.0/">CC BY 3.0</a>.

nav:
  - Home: index.md
  - Learn:
    - Handbook: osg_handbook.md
  - Play:
    - Contested Ground: contested_ground.md
  - Log:
    - Factionlog: factionlog.md
  - Resources: resources.md
  - Blog: blog/index.md

plugins:
  - search
  - blog